package pers.guangjian.hadoken.connector.core.metadata;

import lombok.AllArgsConstructor;
import lombok.Getter;

/**
 * 设备管理相关特性
 *
 * @author yanggj
 * @version 1.0.0
 * @date 2022/10/12 9:57
 */
@Getter
@AllArgsConstructor
public enum ManagementFeature implements Feature {

    autoGenerateDeviceId("自动生成设备ID");

    private final String name;

    @Override
    public String getId() {
        return name();
    }

    @Override
    public String getType() {
        return "device-manage";
    }
}

